name: voice_notes_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  # StateManagment 
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  # Styling And Assets
  flutter_feather_icons: ^2.0.0+1
  flutter_svg: ^2.0.10+1
  # Pagination
  infinite_scroll_pagination: ^4.0.0
  # Date Formating
  intl: ^0.19.0
  # Recording And Playing Audios
  just_audio: ^0.9.39
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  record: ^5.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: dubai
      fonts:
        - asset: assets/fonts/Dubai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dubai-Medium.ttf
          weight: 500
        - asset: assets/fonts/Dubai-Regular.ttf
          weight: 400



